/*
 * generated by Xtext 2.29.0
 */
package de.davidmpaz.ui.outline;

import org.eclipse.xtext.ui.editor.outline.IOutlineNode;
import org.eclipse.xtext.ui.editor.outline.impl.DefaultOutlineTreeProvider;

import de.davidmpaz.logBook.LogEntry;
import de.davidmpaz.logBook.Task;

/**
 * Customization of the default outline structure.
 *
 * See https://www.eclipse.org/Xtext/documentation/310_eclipse_support.html#outline
 */
public class LogBookOutlineTreeProvider extends DefaultOutlineTreeProvider {

	/**
	 * Tasks are leafs in the tree
	 * 
	 * Task can not be expanded anymore
	 * 
	 * @param task
	 * @return
	 */
	protected boolean _isLeaf(Task task) {
		return true;
	}
	
	/**
	 * Show a Day Log Entry as leaf if empty
	 * 
	 * @param day
	 * @return
	 */
	protected boolean _isLeaf(LogEntry day) {
		return day.getTasks().size() < 1;
	}
	
	/**
	 * Avoid creating a child element for the date
	 * 
	 * Show only tasks under entry log, date is shown already as parent node
	 * 
	 * @param parentNode
	 * @param domainModel
	 */
	protected void _createChildren(IOutlineNode parentNode, LogEntry domainModel) {
		for (Task task: domainModel.getTasks()) {
			createNode(parentNode, task);
		}
	}
}
