/*
 * generated by Xtext 2.29.0
 */
package de.davidmpaz.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class LogBookUiModule extends AbstractLogBookUiModule {

	public LogBookUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
