/*
 * generated by Xtext 2.29.0
 */
package de.davidmpaz.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import de.davidmpaz.LogBookRuntimeModule;
import de.davidmpaz.LogBookStandaloneSetup;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class LogBookIdeSetup extends LogBookStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new LogBookRuntimeModule(), new LogBookIdeModule()));
	}
	
}
