/*
 * generated by Xtext 2.29.0
 */
package de.davidmpaz;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class LogBookStandaloneSetup extends LogBookStandaloneSetupGenerated {

	public static void doSetup() {
		new LogBookStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
