/*
 * generated by Xtext 2.29.0
 */
package de.davidmpaz;


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class LogBookRuntimeModule extends AbstractLogBookRuntimeModule {
}
